export const END_POINTS = {
  SIGN_UP: '/users',
  SIGN_IN: '/oauth/token',
  STYLES: '/styles',
  COLORS: '/colours',
  ARTWORKS: '/artworks',
  GALLERIES: '/galleries',
  GALLERY: '/gallery',
  ARTISTS: '/artists',
  EXHIBITIONS: '/exhibitions',
  FEATURES: '/artworks/featured',
  INSIGHTS: '/insights',
  PROFILE: '/profile',
  EXHIBITION_STYLES: '/exhibition_styles',
  PACKAGES: '/packages',
  SUBSCRIPTION: '/subscriptions',
  GALLERYMOCK: '/exhibitions/by_key',
  GET_PRICING_DATA: '/get_pricing_data',
  PRICE_SHEETS: '/price_sheets',
  SEARCH_ARTIST: '/search_artist',
  ARTWORKS_PRICE: 'get_paper_and_price',
  ORDERS: '/orders',
  FAQS: '/faqs',
  SETTINGS: '/artist_settings',
  CURRENCIES: '/store_currencies',
};

export const LINKS = {
  HOME: '/',
  STORE: '/store',
  My_PROFILE: '/my-profile',
};
